# 端口号，项目上下文路径
server:
  port: 8080
  servlet:
    context-path: /yjxms

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/yjxms?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      validation-query: select 1

  # freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8

  # 启动热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

# Mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.yjxxt.bean;com.yjxxt.query;com.yjxxt.dto
  configuration:
    map-underscore-to-camel-case: true

# pageHelper
pagehelper:
  helper-dialect: mysql

# 设置日志级别
logging:
  level:
    com:
      yjxxt:
        mapper: debug
